### ISSUE TITLE
How to do modulo operations?

### ISSUE THREAD

**Issue by boyum** [emojicode/emojicode.github.io#24]
I might be blind, but even after looking through the documentation a few times, I haven't encountered any modulo operation examples. I've seen that the compiler uses `0x25` for this, but I have no idea what to do with this knowledge.

Also, you have perhaps done this on purpose, but it would be a bit easier (for me, at least) to find what I'm looking for, had the documentation used more common keywords like "for loops" or "if statements". Even though this might not be entirely correct for some reason, I find knowing what to search for incredibly hard.

Nice work, anyways. Keep it up!

**Comment by thbwd** [comment]
The modulo operator is a method of 🚂 and therefore documented in the s package documentation: http://www.emojicode.org/docs/packages/s/1f682.html#m🚮

You’re right about that the current documentation often does not use common keywords (for various reasons), but that's something that's going to be improved in the documentation for Emojicode 0.5. You can already have a look at it on the 0.5 branch. https://github.com/emojicode/emojicode.github.io/blob/0.5/src/reference/controlflow.md, for instance, has already been improved similar to what you suggested. Feedback is, of course, always welcome!

**Comment by boyum** [comment]
Aha, thanks!
