### ISSUE TITLE
Incorrect Pig Latin Definition

### ISSUE THREAD

**Issue by bpsizemore** [emojicode/emojicode.github.io#26]
One of the example programs is to convert English to Piglatin. I like this idea, but the definition of Pig Latin is actually incorrect.  
 According to Google ```...formed from English by transferring the initial consonant or consonant cluster of each word to the end of the word...```  
Notice that it is the initial consonant or consonant cluster. The included definition is ```the Pig Latin word you just have to move the first letter of the English word to the end```  
The example tests are only words that start with a single consonant followed by a vowel. 

Here is the link to relevant page in your docs. http://www.emojicode.org/docs/guides/compile-and-run.html

**Comment by thbwd** [comment]
Right, that's definitely not pig latin. Don’t know what I was thinking when I wrote that.

Probably we should just add that it's a very simplified version of pig latin? Or extend the tutorial to at least in the end really produce pig latin words?

**Comment by bpsizemore** [comment]
Sounds fair, give me a few days and I'll PR with either a slightly different example that shows off the same simplicity/features of the language or get it to produce actual pig latin.
