### ISSUE TITLE
Confusing sentence in section on Optionals in ref manual

### ISSUE THREAD

**Issue by mshulman** [emojicode/emojicode.github.io#27]
You wrote:

> The point of Optionals is providing more safety. This is achieved by forcing the programmer to take 
> special care of optionals as optionals cannot be used like the they make optionals.

I tried to fix it in a PR, but couldn't actually figure out what you mean by "as optionals cannot be used like the they make optionals."

**Comment by thbwd** [comment]
That's indeed a very mysterious formulation. The whole sentence is somehow odd. Better something like:

> By forcing the programmer to explicitly deal with the case of an absent value, many bugs that could arise when uninitialized values or null pointers were accessed are prevented.
