### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by Daniel-Ko** [emojicode/emojicode.github.io#34]
While compiling the "Howdy Partner" example from the main site, I received the

_The compiler crashed due to an internal problem: std::bad_alloc_ 

message.

I am using Ubuntu for Windows 10 to compile. 

While compiling, my computer slowed down considerably -- almost as if frozen.

**Comment by thbwd** [comment]
You have used the code exactly as shown in this http://www.emojicode.org/docs/guides/compile-and-run.html#greetings example, haven't you?

If so, can you please make sure the source code file is UTF8 encoded. If that doesn't help or the file is already UTF8, please tell me the version of Ubuntu being emulated. (You are using Emojicode 0.5.1, right?)

**Comment by Daniel-Ko** [comment]
Apologise for the late reply.

I tried both your suggestions and the compilation worked successfully, meaning the problem was either the UTF encoding or doing a 4-space tab indent instead of the example code's 2-space indent (I think).

When running the greeter emojib, however, now I am receiving a 
"version 'GLIBCXX_3.4.22' not found"

and I have tried 
"apt-get install libstdc++6"
 as well as
"sudo apt-get dist-upgrade"

but the error persists. Please excuse my lack of knowledge in this matter.

For your information, I am using Emojicode 0.5.1 and running Ubuntu 16.04.2

**Comment by thbwd** [comment]
The compiler most certainly did not crash due to another indentation width. 

You should be able to fix your issue with the instructions from https://github.com/emojicode/emojicode/issues/57#issuecomment-313720901.

**Comment by Daniel-Ko** [comment]
Thank you for the instructions. I now have emojicode working.
For future reference, seems closing, not just disabling, Kapersky or 3rd party security software and running Bash on WSL as admin solves most connection issues.
