### ISSUE TITLE
Missing code sample

### ISSUE THREAD

**Issue by colinking** [emojicode/emojicode.github.io#5]
The code sample demoing an initialization of a class is missing from the docs page [here](http://www.emojicode.org/docs/reference/classes.html). The previous code sample, showing how to create a class, is shown instead.

![image](https://cloud.githubusercontent.com/assets/2907397/13551741/46b7a7c8-e312-11e5-9fd1-1e171153a4f1.png)

**Comment by thbwd** [comment]
Something definitely went wrong here. I'll fix that.
