### ISSUE TITLE
File Loading Example Code Compilation Error

### ISSUE THREAD

**Issue by bhainesva** [emojicode/emojicode.github.io#74]
I tried to use this example from the page about packages: https://www.emojicode.org/docs/reference/packages.html#importing-other-packages

```
📦 files 🏠

🏁 🍇
  🍺🆕📄📜 🔤novel.txt🔤❗️ ➡️ readFile
🍉
```

but the compiler gives me this error:

```
2-1.emojic:4:22: 🚨 error: Unexpected token RightProductionOperator.
  🍺🆕📄📜 🔤novel.txt🔤❗️ ➡️ readFile
                     ⬆️
```

**Comment by thbwd** [comment]
#73, which I have just merged, fixes this. 😄
