### ISSUE TITLE
Generics Example Compilation Error

### ISSUE THREAD

**Issue by bhainesva** [emojicode/emojicode.github.io#75]
I am trying to run an example from the generics documentation page: https://www.emojicode.org/docs/reference/generics.html
``` 
🍨🔤aa🔤 🔤12345🔤🍆 ➡️ list
🐰 list 🐚🔡🍆 🍇 a 🔡 ➡️ 🔡
  ↩️ 🔤🧲a🧲!🔤
🍉
```

Compiling gives me the error: 
```
2-1.emojic:3:18: 🚨 error: Unexpected token RightProductionOperator.
  🍨🔤aa🔤 🔤12345🔤🍆 ➡️ list
                 ⬆️
```

I tried changing the 🍨 to 🍿 after seeing this issue: https://github.com/emojicode/emojicode.github.io/issues/65 but then I get the error, which I'm unsure of how to fix:
```
2-1.emojic:4:10: 🚨 error: Unexpected token Generic.
  🐰 list 🐚🔡🍆 🍇 a 🔡 ➡️ 🔡
         ⬆️
```

The example with type inference:
```
  🐰 list 🍇 a 🔡 ➡️ 🔡
    ↩️ 🔤🧲a🧲!🔤
  🍉
```
also gave me an `Unexpected token BlockEnd` but I think I was able to fix it by adding an ❗️.

**Comment by thbwd** [comment]
The documentation is totally out of date concerning generics in several places it appears. This should work:

```
🏁 🍇
  🍿🔤aa🔤 🔤12345🔤🍆 ➡️ list
  🐰🐚🔡🍆 list 🍇 a 🔡 ➡️ 🔡
    ↩️ 🔤🧲a🧲!🔤
  🍉❗️
🍉
```
