### ISSUE TITLE
Invalid Examples in Classes & Value Types Language Reference

### ISSUE THREAD

**Issue by flwyd** [emojicode/emojicode.github.io#79]
The example in [Mutability of Value Types](https://www.emojicode.org/docs/reference/classes-valuetypes.html#mutability-of-value-types) which calls the 🗝 method on `credit_card` is rejected by the compiler with `🚨 error: _💳 has no suitable 🗝` because 🗝 expects a string argument.
(Bonus typo in the same section: "Only value types in a mutable variables are mutable" in that section should either drop the "a" or change "mutable variables" to singular.)

The example code in [Type Methods](https://www.emojicode.org/docs/reference/classes-valuetypes.html#type-methods) is rejected by the compiler (`Emojicode-1.0-beta.2-Darwin-x86_64`).
```
🐇 🍕 🍇
  📗 Return available pizza dishes. 📗
  🐇❗️ 📜 ➡️ 🍨🐚🔡🍆 🍇
    ↩️ 🍨 🔤Margherita🔤 🔤Tonno🔤 🔤Quattro Formaggi🔤 🍆
  🍉
🍉
```
```
pizza.emojic:3:5: 🚨 error: Unexpected token DocumentationComment.
    📗 Return available pizza dishes. 📗
    ⬆️
```
Removing the documentation section results in the error
```
pizza.emojic:3:6: 🚨 error: Expected Identifier but instead found EndOfArguments(❗).
    🐇❗️ 📜 ➡️ 🍨🐚🔡🍆 🍇
     ⬆️
```
I suspect it would also balk at the return line for using 🍨 instead of 🍿.

**Comment by thbwd** [comment]
After replacing 🍨  with 🍿 the type method example worked for me. Not sure why you were seeing that error.
