### ISSUE TITLE
Operators Aren't Fully Defined

### ISSUE THREAD

**Issue by flwyd** [emojicode/emojicode.github.io#80]
The [operators](https://www.emojicode.org/docs/reference/operators.html) section of the language guide should explain the semantics of each operator for basic types.  It's implied that ➗, ✖️, ➖, ➕ are the standard arithmetic operators.  🤝 and 👐 are explained as logical `and` and `or`.  😜 is defined as the identity check operator and says to use 😛 for value equality, but 😛 is not part of the BNF for `binary-operator` at the top of the page, nor in the operator precedence list.  The remaining 11 operators in the `binary-operator` declaration are not explained.

The operators with highest precedence (🔲, ⬛, 🔺, ⁉️, 🍺) are not part of the BNF for `binary-operator` and I have absolutely no clue what they might mean as operators.

The Operator Precedence section says "Operators at top are evaluated first" but does not specify how operators with the same precedence are handled.  (One might guess that they're left-associative, but this should be stated explicitly.)

**Comment by thbwd** [comment]
See also #71. The meaning of operators is technically up to each class, but I agree some words about their common meaning wouldn't be bad.
"🔲, ⬛, 🔺, ⁉️, 🍺" have their own grammar rules like ["cast"](https://www.emojicode.org/docs/reference/types.html#srule-cast) or ["unwrap"](https://www.emojicode.org/docs/reference/optionals.html#srule-unwrap) and actually are prefix operators. Adding explanation of what all operators mean, will probably also resolve this.
