### ISSUE TITLE
Invalid Example in Protocol Guide

### ISSUE THREAD

**Issue by flwyd** [emojicode/emojicode.github.io#81]
The example in [Calling Methods on Protocol Types](https://www.emojicode.org/docs/reference/protocols.html#calling-methods-on-values-of-protocol-type) does not compile with `Emojicode-1.0-beta.2-Darwin-x86_64`:

```
🐊 💿 🍇
  ❗️🎶
🍉

🐇  📱 🍇
  🐊 💿

  ❗️ 🎶 🍇
    😀 🔤Lalalala🔤❗️
  🍉
🍉

🏁🍇
  🖍 🆕 cd_like 💿
  🆕📱  ➡️ 🖍  cd_like
  🎶 cd_like❗️
🍉
```
produces
```
protocol.emojic:15:7: 🚨 error: Unexpected token RightProductionOperator.
  🆕📱  ➡️ 🖍 cd_like
      ⬆️
```

Changing the assignment line to `🆕📱 ❗️ ➡️ 🖍  cd_like` (addition of ❗️)  produces
```
protocol.emojic:15:3: 🚨 error: _📱 has no suitable 🆕.
  🆕📱 ❗️ ➡️ 🖍 cd_like
  ⬆️
```

Additionally, the BNF for `protocol` does not specify that it uses the grapes-watermelon 🍇🍉 block delimiters to surround the `protocol-body`, but all of the examples imply that it's required.

**Comment by thbwd** [comment]
I've added an initializer, but I think in several other locations implementing a trivial initializer was "left as an exercise for the reader".
