### ISSUE TITLE
Make the Docs more user-friendly

### ISSUE THREAD

**Issue by joeskeen** [emojicode/emojicode.github.io#86]
## ⭐️ Proposed change

Make it possible to search and/or cross-reference the documentation.

## 🤔 Rationale

One of the most frustrating things for a new developer getting into Emojicode is when you are reading the docs and you see an emoji (or a bunch of emoji) that you don't know what it means, and the documentation doesn't have any explanation about it. I would love to be able to either:

* Search for the emoji and see other places in the docs it's referenced or defined
* Hover/click on an emoji to see a tooltip description or link to its definition

Luckily, I'm very stubborn and eventually figure it out, but it's a problem I've had soooo many times and I'm sure I'm not alone.

## 🕺 Additional remarks

It looks like Doxygen creates some search stuff by default, but it doesn't look like it's in use in the docs site. I imagine that this is because it doesn't really work or isn't useful? Could we tweak Doxygen to improve it and make it usable?

If we did want to do tooltips, we would likely need to create an index that maps emoji to a definition and do some post-processing on the Doxygen-generated docs to add the tooltips.

If we did want to do cross-referencing, we would likely need to create an index that maps emoji to a URL (with `#` to the id of the section) and do some post-processing on the Doxygen-generated docs to add the links.

**Comment by thbwd** [comment]
Thanks for taking the time to share your experience. 

I agree on-site search would be helpful, and I've therefore applied to Algolia Docsearch just now. Hopefully, they'll get back soon, and I can integrate their search. For the time being, Google yields the right pointers into the documentation for "emojicode read file" or "emojicode split string" for me.

The Emojicode Documentation doesn't use Doxygen. The source for the documentation is in this repository if you want to look at it. (We use Doxygen to document the C++ implementation of the compiler, though.)

It isn't as trivial to map emojis to some meaning as it might sound, as the meaning of an emoji depends on its context. For example, 🖍 or even 🔵 can mean different things depending on where they occur, as in many other programming languages. Therefore, the kind of pop-ups you propose would require parsing the source code of each example with the compiler and then using the AST, which is a lot of work.

One thing that might help — from the many questions I've answered over the years — would be to create a section in the documentation with answers (examples) to common questions. Like "How do I read a file?", "How do I break from a loop?" etc. Do you think this would improve the experience?

Finally, I'd invite you to submit any improvements that you can make as pull requests.

**Comment by joeskeen** [comment]
I do think a "recipes" or common use cases section would be very helpful. Perhaps even a "cheat sheet" that shows most of the reserved emoji and what they do (you could have context-specific examples). If users knew the cheat sheet was only one click away, perhaps other optimizations of the docs would be unnecessary.

**Comment by thbwd** [comment]
The docs now feature DocSearch: https://www.emojicode.org/docs/

**Comment by joeskeen** [comment]
I am loving the new search feature! Thanks for implementing it!
